theme: jekyll-theme-minimal
logo: "assets/img/logo.png"
title: "Odias in Machine Learning"
description: "The machine learning global community of Odias"
show_downloads: false
social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali